### PR TITLE
Fix mangohud buliding with option -Dwith_xnvctrl=disabled and -Dwith_nvml=enabled

### LINKED ISSUE #1008: Mangohud failed to build with -Dwith_xnvctrl=disabled and -Dwith_nvml=enabled
Since commit cbf531e6c83a6eff928f80b7399a06dfb1484593

There are error when compiling mangohud with option `-Dwith_xnvctrl=disabled`and `-Dwith_nvml=enabled`

    [63/64] Linking target src/libMangoHud.so
    FAILED: src/libMangoHud.so 
    c++  -o src/libMangoHud.so src/libMangoHud.a.p/mesa_util_os_socket.c.o src/libMangoHud.a.p/mesa_util_os_time.c.o src/libMangoHud.a.p/hud_elements.cpp.o src/libMangoHud.a.p/overlay.cpp.o src/libMangoHud.a.p/overlay_params.cpp.o src/libMangoHud.a.p/font.cpp.o src/libMangoHud.a.p/keybinds.cpp.o src/libMangoHud.a.p/font_unispace.c.o src/libMangoHud.a.p/logging.cpp.o src/libMangoHud.a.p/config.cpp.o src/libMangoHud.a.p/gpu.cpp.o src/libMangoHud.a.p/vulkan.cpp.o src/libMangoHud.a.p/blacklist.cpp.o src/libMangoHud.a.p/file_utils.cpp.o src/libMangoHud.a.p/intel.cpp.o src/libMangoHud.a.p/cpu.cpp.o src/libMangoHud.a.p/memory.cpp.o src/libMangoHud.a.p/iostats.cpp.o src/libMangoHud.a.p/notify.cpp.o src/libMangoHud.a.p/elfhacks.cpp.o src/libMangoHud.a.p/real_dlsym.cpp.o src/libMangoHud.a.p/pci_ids.cpp.o src/libMangoHud.a.p/battery.cpp.o src/libMangoHud.a.p/control.cpp.o src/libMangoHud.a.p/gamepad.cpp.o src/libMangoHud.a.p/amdgpu.cpp.o src/libMangoHud.a.p/nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvml.cpp.o src/libMangoHud.a.p/loaders_loader_x11.cpp.o src/libMangoHud.a.p/shared_x11.cpp.o src/libMangoHud.a.p/dbus.cpp.o src/libMangoHud.a.p/loaders_loader_dbus.cpp.o src/libMangoHud.a.p/gl_glad.c.o src/libMangoHud.a.p/gl_gl_renderer.cpp.o src/libMangoHud.a.p/gl_gl_hud.cpp.o src/libMangoHud.a.p/gl_inject_egl.cpp.o src/libMangoHud.a.p/loaders_loader_glx.cpp.o src/libMangoHud.a.p/gl_inject_glx.cpp.o src/libMangoHud.a.p/meson-generated_.._.._vk_enum_to_str.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud.so src/libMangoHud.a subprojects/imgui-1.81/libimgui.a subprojects/spdlog-1.8.5/src/libspdlog.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -lGL -Wl,--end-group -Wl,--version-script,/mnt/WD4TBBTRFS/billli11/git/Mangohud/src/mangohud.version -pthread
    /usr/bin/ld: src/libMangoHud.a.p/gpu.cpp.o: in function `getNvidiaGpuInfo(overlay_params const&)':
    gpu.cpp:(.text+0x2bc): undefined reference to `checkXNVCtrl()'
    /usr/bin/ld: gpu.cpp:(.text+0x311): undefined reference to `getNvctrlFanSpeed()'
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.

Reverting the commit fix the problem.

### PR DESCRIPTION
**Pull request by Billli11**
Fix #1008

Use existing identifier `HAVE_XNVCTRL` to check if xnvctrl is available

### CODE REVIEW

**Review by nik6ena — CHANGES_REQUESTED** [review]
Shouldn't we also guard the inclusion of `nvctrl.h`?

**Comment by nik6ena** [comment]
I get you. But it's only logical to add it into this change set.

I don't know weather `XNVCtrl​` package exports this `nvctrl.h​`, but it could lead to same error, in future builds.
------- Original Message -------

**Review by nik6ena — COMMENTED** [review]
Good work.

Next time just don't indent preprocessor directives. Every other codebase sticks to this practice of keeping it flat, on level one.
