### ISSUE TITLE
building Mangohud-0.8.0 -rc2 from the DFSG source fails

### ISSUE THREAD

**Issue by aur-r** [flightlessmango/MangoHud#1552]
Building Mangohud-v0.8.0-rc2 from the "DFSG" source fails with the compiler complaining about the file 'nvml.h' missing. 
BTW, compiling from the git or the full source works fine.

If it is of any help, this is the compiler error message:

`g++ -Isrc/libMangoHud.a.p -Isrc -I../src -I../include -Isubprojects/imgui-1.89.9 -I../subprojects/imgui-1.89.9 -I../subprojects/imgui-1.89.9/backends -I../subprojects/Vulkan-Headers-1.2.158/include -Isubprojects/implot-0.16 -I../subprojects/implot-0.16 -I. -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -fvisibility=hidden -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -Werror=missing-declarations -Werror=return-type -Wno-unused-parameter -fno-math-errno -fno-trapping-math -Wno-non-virtual-dtor -Wno-missing-field-initializers -O2 -g -pipe -Wformat -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -fomit-frame-pointer -m32 -march=i686 -msse2 -mtune=generic -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection=full -fPIC -pthread -DSPDLOG_SHARED_LIB -DSPDLOG_FMT_EXTERNAL '-DIMGUI_API=__attribute__((visibility("default")))' -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS '-DPACKAGE_VERSION="v0.8.0"' -DSPDLOG_COMPILED_LIB -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_DEBUG -D_GNU_SOURCE -DHAVE_PTHREAD -DUSE_GCC_ATOMIC_BUILTINS -DHAVE_TIMESPEC_GET -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE '-DMANGOHUD_ARCH="32bit"' -DHAVE_X11 -DHAVE_WAYLAND -DHAVE_DBUS -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_WAYLAND_KHR -MD -MQ src/libMangoHud.a.p/nvidia.cpp.o -MF src/libMangoHud.a.p/nvidia.cpp.o.d -o src/libMangoHud.a.p/nvidia.cpp.o -c ../src/nvidia.cpp
../src/nvidia.cpp:1:10: fatal error: nvml.h: No such file or directory
    1 | #include "nvml.h"
      |          ^~~~~~~~
compilation terminated.
`

Regards.

**Comment by 17314642** [comment]
That's because you downloaded DFSG version of source code. (https://wiki.debian.org/DebianFreeSoftwareGuidelines)

nvml.h - is nvidia header related to gathering nvidia GPU stats. If you don't need it, just do 

`./build.sh configure -Dwith_nvml=disabled`

Otherwise, download the usual source, not dfsg one.

**Comment by aur-r** [comment]
@17314642 
I'm sorry for not mentioning that I'm using meson for building, and "-Dwith_nvml=disabled" is set for DFSG source. It used to work with version 0.7.2, but now it fails. From my understanding, the DFSG source is generated to stay clear of NVIDIA licensing issues.

This is the full meson command I'm using:
`/usr/bin/meson setup --buildtype=plain --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . build -Dmangoapp=true -Dmangohudctl=true -Dinclude_doc=true -Duse_system_spdlog=enabled -Dwith_wayland=enabled -Dwith_nvml=disabled -Dwith_xnvctrl=disabled -Dwith_x11=enabled -Dtests=enabled`

**Comment by 17314642** [comment]
Try to replace first line in nvidia.cpp with this:

```
#ifdef HAVE_NVML
#include "nvml.h"
#endif
```

**Comment by aur-r** [comment]
@17314642  That works, thanks.
