### ISSUE TITLE
DBus-less build is broken with Clang

### ISSUE THREAD

**Issue by danfe** [flightlessmango/MangoHud#327]
When I build with `-Dwith_dbus=disabled`, Clang 10.0.1 on FreeBSD emits the following errors:
```
../src/overlay.cpp:2614:31: error: implicit instantiation of undefined template 'std::__1::array<VkPresentModeKHR, 4>'
  array<VkPresentModeKHR, 4> modes = {

../src/overlay_params.cpp:544:31: error: implicit instantiation of undefined template 'std::__1::array<unsigned int *, 11>'
  std::array<unsigned *, 11> colors = {
```
It looks like `#include <array>` is missing in both files (adding it fixes the build).

The problem does not exhibit itself against the default settings because this header is included in the `src/dbus_info.h` file.

**Comment by jackun** [comment]
And that's why it's good to test multiple compilers :P
